'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Loader2, FileText, Layers, ArrowLeft, RefreshCw, Calendar } from 'lucide-react'
import api from '@/lib/api-client'
import Link from 'next/link'

interface TeacherContent {
    id: string
    title: string
    subject: string
    grade_level: string
    created_at: string
    content_type: 'lesson_plan' | 'deck'
    teacher_id: string
    teacher_name: string
    teacher_email: string
}

export default function TeacherContentPage() {
    const [content, setContent] = useState<TeacherContent[]>([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)
    const [contentTypeFilter, setContentTypeFilter] = useState<string>('all')
    const [page, setPage] = useState(1)
    const [totalCount, setTotalCount] = useState(0)
    const limit = 20

    const fetchContent = async () => {
        setLoading(true)
        setError(null)
        try {
            const params = new URLSearchParams({
                page: page.toString(),
                limit: limit.toString(),
            })
            if (contentTypeFilter !== 'all') {
                params.append('contentType', contentTypeFilter)
            }

            const response = await api.get(`/admin/teacher-content?${params}`)
            setContent(response.data.content)
            setTotalCount(response.data.totalCount)
        } catch (err: any) {
            setError(err.response?.data?.message || 'Failed to fetch teacher content')
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        fetchContent()
    }, [page, contentTypeFilter])

    const formatDate = (dateString: string) => {
        return new Date(dateString).toLocaleString('en-IN', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        })
    }

    const handleDelete = async (id: string, contentType: string, title: string) => {
        if (!confirm(`Are you sure you want to delete "${title}"? This action cannot be undone.`)) {
            return
        }

        try {
            await api.delete(`/admin/teacher-content/${contentType}/${id}`)
            setContent(prev => prev.filter(item => !(item.id === id && item.content_type === contentType)))
            setTotalCount(prev => prev - 1)
        } catch (err: any) {
            setError(err.response?.data?.message || 'Failed to delete content')
        }
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <Link href="/dashboard">
                        <Button variant="outline" size="sm" className="mb-4">
                            <ArrowLeft className="h-4 w-4 mr-2" />
                            Back to Dashboard
                        </Button>
                    </Link>
                    <h1 className="text-3xl font-bold text-gray-900">Teacher Generated Content</h1>
                    <p className="text-muted-foreground mt-1">
                        View all lesson plans and decks created by teachers
                    </p>
                </div>
                <Button onClick={fetchContent} variant="outline" disabled={loading}>
                    <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
                    Refresh
                </Button>
            </div>

            <Card>
                <CardHeader className="border-b bg-slate-50">
                    <div className="flex items-center justify-between">
                        <div>
                            <CardTitle>Content Overview</CardTitle>
                            <CardDescription>
                                {totalCount} total items generated by teachers
                            </CardDescription>
                        </div>
                        <div className="flex items-center gap-4">
                            <Select value={contentTypeFilter} onValueChange={setContentTypeFilter}>
                                <SelectTrigger className="w-[180px]">
                                    <SelectValue placeholder="Filter by type" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">All Content</SelectItem>
                                    <SelectItem value="lesson_plan">Lesson Plans</SelectItem>
                                    <SelectItem value="deck">Decks</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                </CardHeader>
                <CardContent className="p-0">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <Loader2 className="h-8 w-8 animate-spin text-indigo-600" />
                        </div>
                    ) : error ? (
                        <div className="text-center py-12 text-red-500">{error}</div>
                    ) : content.length === 0 ? (
                        <div className="text-center py-12 text-muted-foreground">
                            No content found
                        </div>
                    ) : (
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Type</TableHead>
                                    <TableHead>Title</TableHead>
                                    <TableHead>Subject</TableHead>
                                    <TableHead>Grade</TableHead>
                                    <TableHead>Teacher</TableHead>
                                    <TableHead>Created At</TableHead>
                                    <TableHead className="text-right">Actions</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {content.map((item) => (
                                    <TableRow key={`${item.content_type}-${item.id}`}>
                                        <TableCell>
                                            <Badge
                                                variant="outline"
                                                className={item.content_type === 'lesson_plan'
                                                    ? 'border-indigo-200 text-indigo-700 bg-indigo-50'
                                                    : 'border-emerald-200 text-emerald-700 bg-emerald-50'
                                                }
                                            >
                                                {item.content_type === 'lesson_plan' ? (
                                                    <><FileText className="h-3 w-3 mr-1" /> Lesson Plan</>
                                                ) : (
                                                    <><Layers className="h-3 w-3 mr-1" /> Deck</>
                                                )}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="font-medium max-w-[200px] truncate">
                                            {item.title}
                                        </TableCell>
                                        <TableCell className="capitalize">{item.subject}</TableCell>
                                        <TableCell>Grade {item.grade_level}</TableCell>
                                        <TableCell>
                                            <div>
                                                <div className="font-medium">{item.teacher_name}</div>
                                                <div className="text-xs text-muted-foreground">{item.teacher_email}</div>
                                            </div>
                                        </TableCell>
                                        <TableCell>
                                            <div className="flex items-center gap-1 text-sm text-muted-foreground">
                                                <Calendar className="h-3 w-3" />
                                                {formatDate(item.created_at)}
                                            </div>
                                        </TableCell>
                                        <TableCell className="text-right">
                                            <Button
                                                variant="ghost"
                                                size="sm"
                                                className="text-red-600 hover:text-red-700 hover:bg-red-50"
                                                onClick={() => handleDelete(item.id, item.content_type, item.title)}
                                            >
                                                Delete
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    )}
                </CardContent>
            </Card>

            {/* Pagination */}
            {totalCount > limit && (
                <div className="flex items-center justify-between">
                    <p className="text-sm text-muted-foreground">
                        Showing {(page - 1) * limit + 1} to {Math.min(page * limit, totalCount)} of {totalCount}
                    </p>
                    <div className="flex gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setPage(p => Math.max(1, p - 1))}
                            disabled={page === 1 || loading}
                        >
                            Previous
                        </Button>
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setPage(p => p + 1)}
                            disabled={page * limit >= totalCount || loading}
                        >
                            Next
                        </Button>
                    </div>
                </div>
            )}
        </div>
    )
}
